/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/masuk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Masuk
         * @description Login nomor HP + PIN 6 digit (§9.1).
         */
        post: operations["masuk_api_auth_masuk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/masuk-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Masuk Demo
         * @description Masuk cepat (demo) — hanya aktif saat DEMO_MODE (§9.1, K6: 6 akun).
         */
        post: operations["masuk_demo_api_auth_masuk_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saya
         * @description Profil pengguna yang sedang login.
         */
        get: operations["saya_api_auth_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aturan-kiriman": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aturan Kiriman
         * @description K14: ambang kiriman untuk divalidasi di layar Kirim Panen — supaya petani
         *     tahu batasnya SEBELUM menekan tombol, bukan lewat galat 422 sesudahnya.
         */
        get: operations["aturan_kiriman_api_aturan_kiriman_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komoditas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Komoditas */
        get: operations["daftar_komoditas_api_komoditas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/penerima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Penerima */
        get: operations["daftar_penerima_api_penerima_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titik-kumpul/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Titik Kumpul Saya
         * @description Titik kumpul milik pengguna login (titik awal rute). Rename v2 §2: dulu /koperasi/saya.
         */
        get: operations["titik_kumpul_saya_api_titik_kumpul_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wilayah/cari": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cari Wilayah
         * @description Autocomplete daerah dari tabel `wilayah` (data Kemendagri, di-seed lokal).
         *
         *     Yang diawali kata kunci diutamakan daripada yang sekadar mengandungnya —
         *     mengetik "cika" harus memunculkan Cikajang lebih dulu, bukan nama panjang
         *     yang kebetulan memuat potongan itu di tengah.
         */
        get: operations["cari_wilayah_api_wilayah_cari_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geokode/balik": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geokode Balik Endpoint
         * @description Koordinat → alamat. Hasilnya di-cache per titik yang dibulatkan, jadi
         *     ketukan berulang di peta tidak pernah memanggil jaringan dua kali.
         */
        get: operations["geokode_balik_endpoint_api_geokode_balik_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konfigurasi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Konfigurasi */
        get: operations["daftar_konfigurasi_api_konfigurasi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konfigurasi/{kunci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah Konfigurasi */
        patch: operations["ubah_konfigurasi_api_konfigurasi__kunci__patch"];
        trace?: never;
    };
    "/api/tier-kendaraan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Tier */
        get: operations["daftar_tier_api_tier_kendaraan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tier-kendaraan/{tier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah Tier */
        patch: operations["ubah_tier_api_tier_kendaraan__tier_id__patch"];
        trace?: never;
    };
    "/api/kiriman": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kirim Panen
         * @description Kirim panen — sistem cocokkan ke muatan (baru atau yang sudah ada, §3.4).
         *     Menggantikan alur 'pilih slot → gabung'.
         *
         *     K14: hanya PETANI. Petugas adalah driver Satu Muatan — dia menjemput dan
         *     mengantar panen orang lain, bukan menyetorkan panennya sendiri.
         */
        post: operations["kirim_panen_api_kiriman_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kiriman/pratinjau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pratinjau
         * @description Pratinjau §3.4 langkah 3: atap + potensi penghematan SEBELUM berkomitmen.
         */
        get: operations["pratinjau_api_kiriman_pratinjau_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Slot
         * @description Ter-scope per peran (K6): PETUGAS -> miliknya; PETANI -> slot titik kumpulnya;
         *     PENERIMA -> slot yang tujuannya memuat dirinya.
         */
        get: operations["daftar_slot_api_slot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/tersedia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slot Tersedia
         * @description K14: PAPAN TUGAS — muatan yang belum punya driver dan berangkat dari titik
         *     kumpul petugas ini.
         *
         *     K13 menugaskan driver otomatis saat muatan lahir, tanpa batas: satu petugas
         *     aktif menyerap SELURUH muatan di sistem, dan tidak ada satu pun endpoint yang
         *     bisa mengubahnya. Sekarang muatan menunggu diambil, dan pengambilan itu
         *     tindakan sadar driver.
         */
        get: operations["slot_tersedia_api_slot_tersedia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/terima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Terima Tugas
         * @description K14: petugas mengambil satu muatan — dan HANYA satu dalam satu waktu.
         *
         *     Batasnya dari konfigurasi (`maks_muatan_aktif_per_petugas`), bukan angka di
         *     kode (CLAUDE.md aturan #1). Sopir tidak bisa membawa dua truk sekaligus;
         *     membiarkannya menumpuk tugas membuat papan tugas jadi hiasan.
         */
        post: operations["terima_tugas_api_slot__slot_id__terima_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Slot
         * @description LAYAR UTAMA DEMO (§9.4). Dipoll 3 detik — harga berjalan, partisipasi,
         *     rencana armada, waktu_server.
         */
        get: operations["detail_slot_api_slot__slot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/gabung": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gabung Slot
         * @description 'Ikut kirim' — mengunci harga_atap_per_kg petani (tidak pernah berubah).
         */
        post: operations["gabung_slot_api_slot__slot_id__gabung_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/gabung/pratinjau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pratinjau Gabung
         * @description Peringatan dini sebelum submit: atap, harga berjalan baru, potensi luapan.
         */
        post: operations["pratinjau_gabung_api_slot__slot_id__gabung_pratinjau_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/tutup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tutup Slot
         * @description Cutoff (§5.4): tetapkan harga final + jaminan atap, kunci rencana armada,
         *     buat lot per partisipasi (alokasi penerima — K6), pesan ke vendor.
         */
        post: operations["tutup_slot_api_slot__slot_id__tutup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/batal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batal Slot */
        post: operations["batal_slot_api_slot__slot_id__batal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/lot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Lot Slot
         * @description Daftar lot sebuah slot — layar Muat (§9.5).
         */
        get: operations["daftar_lot_slot_api_slot__slot_id__lot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/{lot_id}/muat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Muat Lot
         * @description Timbang + foto + grade mutu 1–5 (input kunci atribusi 3-input, spec v2 §6).
         */
        patch: operations["muat_lot_api_lot__lot_id__muat_patch"];
        trace?: never;
    };
    "/api/slot/{slot_id}/selesai-muat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Selesai Muat
         * @description Selesai muat -> slot JALAN, waktu berangkat tercatat (§9.5).
         */
        post: operations["selesai_muat_api_slot__slot_id__selesai_muat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/masuk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lot Masuk
         * @description 'Pilih dari daftar' (§9.7) — kenyamanan demo di samping pencarian resi.
         *
         *     K13: akun penerima yang masih terikat satu alamat tetap (data seed) dibatasi
         *     ke alamat itu; akun tanpa ikatan melihat semua lot yang sedang jalan, karena
         *     tujuan kini bebas dan kepemilikan ditentukan oleh nomor resi.
         */
        get: operations["lot_masuk_api_lot_masuk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/qr/{kode_qr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bukti Lot
         * @description Bukti lot dari NOMOR RESI: foto muat, berat, waktu, transit berjalan vs ambang.
         *
         *     K13: tidak ada lagi cek `lot.penerima_id == pengguna.penerima_id`. Tujuan kini
         *     bebas ditulis petani, jadi penerima tidak terikat satu alamat tetap —
         *     memegang nomor resi itu sendiri yang menjadi bukti berhak, persis seperti
         *     surat jalan sungguhan.
         */
        get: operations["bukti_lot_api_lot_qr__kode_qr__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/{lot_id}/serah-terima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Serah Terima
         * @description Terima / Tolak -> atribusi + PENJELASAN (§6, §9.7).
         *
         *     K13: berhak menerima = memegang nomor resinya (lihat `bukti_lot`).
         *     K14: tidak ada lagi "terima dengan potongan", dan TOLAK hanya sah kalau
         *     penurunan mutu yang DIUKUR SISTEM melewati ambang. Aturan itu ditegakkan di
         *     sini, bukan cuma disembunyikan tombolnya — klien tidak boleh dipercaya.
         */
        post: operations["serah_terima_api_lot__lot_id__serah_terima_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/pengiriman": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pengiriman Slot
         * @description Timeline + estimasi tiba (dari ambang transit) + jejak posisi.
         */
        get: operations["pengiriman_slot_api_slot__slot_id__pengiriman_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lacak/{slot_id}/telemetri": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Telemetri Slot
         * @description Sampel telemetri + ringkasan paparan (§5.3). Lazy-generate deterministik
         *     saat pertama dipanggil (SIMULASI, berlabel di UI).
         */
        get: operations["telemetri_slot_api_lacak__slot_id__telemetri_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lacak/resi/{kode_resi}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perjalanan Resi
         * @description K14: seluruh perjalanan satu resi — timeline, jejak posisi, dan telemetri.
         *
         *     Otorisasinya RESI, bukan alamat. `pastikan_bisa_lihat_slot` untuk penerima
         *     masih membandingkan `pengguna.penerima_id` dengan tujuan muatan, dan K13
         *     membuat tujuan bebas — jadi jalur itu tidak lagi bisa dipakai penerima yang
         *     sah. Memegang nomor resi adalah buktinya, persis seperti surat jalan.
         */
        get: operations["perjalanan_resi_api_lacak_resi__kode_resi__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pengiriman/{pengiriman_id}/majukan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Majukan Pengiriman
         * @description Majukan state simulasi MockVendor satu langkah (K5) — deterministik, untuk demo.
         */
        post: operations["majukan_pengiriman_api_pengiriman__pengiriman_id__majukan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pengiriman/{pengiriman_id}/geser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Geser Posisi
         * @description K13: majukan POSISI kendaraan satu langkah sepanjang rute, bukan status.
         *
         *     Tiap panggilan menulis satu titik `JejakPosisi` hasil interpolasi + satu
         *     sampel telemetri, sehingga peta benar-benar bergerak saat didemokan.
         *     Langkah terakhir menandai TIBA. Dipakai tombol "Majukan posisi" dan mode
         *     "jalan otomatis" di layar Lacak.
         */
        post: operations["geser_posisi_api_pengiriman__pengiriman_id__geser_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/berita-acara": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Berita Acara
         * @description Agregat: lot + foto muat & bongkar, keputusan, atribusi, rincian ongkos
         *     per petani, selisih jaminan atap. Tanda tangan = garis kosong cetak (K4).
         */
        get: operations["berita_acara_api_slot__slot_id__berita_acara_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dampak/ringkasan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dampak Ringkasan
         * @description Empat kartu semboyan (spec v2 §7.1) — satu angka per semboyan, masing-masing
         *     dengan rumus + status_sumber. Tanpa data = null -> '—'. Urutan JANGAN diubah.
         */
        get: operations["dampak_ringkasan_api_dampak_ringkasan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dampak/bulanan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dampak Bulanan
         * @description Grafik batang per bulan (Recharts) — termasuk jumlah_kiriman (K6).
         */
        get: operations["dampak_bulanan_api_dampak_bulanan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partisipasi/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Partisipasi Saya
         * @description Riwayat ikut kirim + kembalian milik petani login.
         */
        get: operations["partisipasi_saya_api_partisipasi_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Demo
         * @description Kembalikan database ke keadaan awal skenario demo (§11.2). Idempoten,
         *     deterministik — memanggil fungsi bersama `reset_ke_awal_demo` (Fase 3,
         *     `backend/seed/skenario_demo.py`) supaya CLI (`python seed/skenario_demo.py`)
         *     dan endpoint ini TIDAK PERNAH berbeda perilaku.
         *
         *     Data transaksional dikosongkan KECUALI 8 slot riwayat SELESAI (spec §11.1 —
         *     sumber grafik Dashboard Dampak); master (koperasi, penerima, komoditas,
         *     pengguna) + tier tetap utuh; konfigurasi dikembalikan ke nilai default seed.
         */
        post: operations["reset_demo_api_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/muatan/{slot_id}/berangkatkan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Berangkatkan Demo
         * @description K13 (tambahan demo): SATU tombol — tutup muatan → terbitkan resi → timbang
         *     otomatis → berangkat, supaya pelacakan bisa langsung didemokan tanpa mengetik
         *     berat & foto satu per satu di depan juri.
         *
         *     Sengaja memanggil ulang handler sungguhan (`tutup_slot`, `selesai_muat`)
         *     supaya jalan pintas ini TIDAK PERNAH menyimpang dari alur asli — kalau alur
         *     aslinya berubah, jalan pintas ini ikut berubah dengan sendirinya.
         */
        post: operations["berangkatkan_demo_api_demo_muatan__slot_id__berangkatkan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AkunDemo
         * @description Akun demo (v2 §8). Tombol masuk cepat di layar Masuk untuk Petugas/Wati/
         *     Dedi/Penerima; Ijah masuk manual via nomor HP + PIN di skenario demo.
         * @enum {string}
         */
        AkunDemo: "PETUGAS" | "PETANI_WATI" | "PETANI_DEDI" | "PETANI_IJAH" | "PENERIMA_CIBIRU";
        /**
         * AlamatIn
         * @description Alamat terstruktur mengikuti standar penulisan ekspedisi Indonesia (K14).
         *
         *     Satu baris teks bebas tidak cukup untuk logistik sungguhan: kurir butuh nama
         *     & nomor telepon yang bisa dihubungi, komponen wilayah yang bisa dibaca
         *     terpisah, kode pos, dan patokan. Surat jalan pun mensyaratkan data pengirim
         *     dan penerima yang lengkap, bukan sekadar "Warung Bu Imas".
         *
         *     Hanya `alamat` (ringkasan) yang wajib — sisanya boleh menyusul supaya petani
         *     tidak terkunci di formulir panjang saat sedang di kebun.
         */
        AlamatIn: {
            /** Alamat */
            alamat: string;
            /** Nama */
            nama?: string | null;
            /** Telepon */
            telepon?: string | null;
            /** Jalan */
            jalan?: string | null;
            /** Rt Rw */
            rt_rw?: string | null;
            /** Desa */
            desa?: string | null;
            /** Kecamatan */
            kecamatan?: string | null;
            /** Kabupaten */
            kabupaten?: string | null;
            /** Provinsi */
            provinsi?: string | null;
            /** Kode Pos */
            kode_pos?: string | null;
            /** Patokan */
            patokan?: string | null;
        };
        /**
         * Atribusi
         * @enum {string}
         */
        Atribusi: "PETANI" | "LOGISTIK" | "TIDAK_TERBUKTI" | "NORMAL";
        /**
         * AturanKirimanOut
         * @description K14: ambang yang harus DIKETAHUI petani sebelum menekan Kirim.
         *
         *     Panel Asumsi hanya boleh dibaca PETUGAS, jadi klien petani dulu tidak punya
         *     cara tahu batas 50 kg — tombol Kirim tetap aktif di 10 kg dan petani baru
         *     ditolak setelah mengirim. Nilainya tetap datang dari tabel `konfigurasi`
         *     (CLAUDE.md aturan #1), bukan ditanam di frontend.
         */
        AturanKirimanOut: {
            /** Volume Minimal Kg */
            volume_minimal_kg: number;
            /** Jarak Maks Layanan Km */
            jarak_maks_layanan_km: number;
        };
        /** BeritaAcaraOut */
        BeritaAcaraOut: {
            /** Kode Slot */
            kode_slot: string;
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            titik_kumpul: components["schemas"]["TitikKumpulOut"];
            /** Tujuan */
            tujuan: components["schemas"]["RuteSegmenOut"][];
            /** Lot */
            lot: components["schemas"]["LotBeritaOut"][];
            /** Rincian Ongkos */
            rincian_ongkos: components["schemas"]["OngkosPetaniOut"][];
            /** Biaya Total */
            biaya_total?: number | null;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /** Selisih Jaminan Atap */
            selisih_jaminan_atap: number;
            /**
             * Dibuat Pada
             * Format: date-time
             */
            dibuat_pada: string;
        };
        /**
         * BuktiLotOut
         * @description Respons GET /api/lot/qr/{kode_qr} — layar Serah Terima (§9.7).
         */
        BuktiLotOut: {
            lot: components["schemas"]["LotOut"];
            /** Durasi Transit Berjalan Menit */
            durasi_transit_berjalan_menit?: number | null;
            /** Ambang Transit Menit */
            ambang_transit_menit: number;
            mutu?: components["schemas"]["IndeksMutuOut"] | null;
            serah_terima?: components["schemas"]["SerahTerimaOut"] | null;
        };
        /**
         * DampakBulananOut
         * @description Satu baris per bulan — juga sumber 'Ringkasan bulan ini' Beranda (§9.2, K6).
         */
        DampakBulananOut: {
            /** Bulan */
            bulan: string;
            /** Jumlah Kiriman */
            jumlah_kiriman: number;
            /** Penghematan Rp */
            penghematan_rp: number;
            /** Truk Km Dihemat */
            truk_km_dihemat: number;
            /** Emisi Kg */
            emisi_kg: number;
            /** Susut Kg */
            susut_kg?: number | null;
        };
        /**
         * DampakRingkasanOut
         * @description Empat kartu semboyan (spec v2 §7.1) — urutan JANGAN diubah.
         */
        DampakRingkasanOut: {
            biaya_logistik: components["schemas"]["KartuDampakOut"];
            emisi: components["schemas"]["KartuDampakOut"];
            transparansi_perjalanan: components["schemas"]["KartuDampakOut"];
            keamanan_pangan: components["schemas"]["KartuDampakOut"];
        };
        /** DemoBerangkatOut */
        DemoBerangkatOut: {
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /** Status */
            status: string;
            /** Pengiriman Id */
            pengiriman_id?: string | null;
            /** Resi */
            resi: string[];
            /** Pesan */
            pesan: string;
        };
        /** DemoResetOut */
        DemoResetOut: {
            /** Pesan */
            pesan: string;
        };
        /** GabungPratinjauRequest */
        GabungPratinjauRequest: {
            /** Volume Kg */
            volume_kg: number;
        };
        /** GabungPratinjauResponse */
        GabungPratinjauResponse: {
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Berjalan Baru Per Kg */
            harga_berjalan_baru_per_kg: number;
            /** Luapan */
            luapan: boolean;
            /** Pesan */
            pesan?: string | null;
        };
        /** GabungRequest */
        GabungRequest: {
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Volume Kg */
            volume_kg: number;
        };
        /** GabungResponse */
        GabungResponse: {
            partisipasi: components["schemas"]["PartisipasiOut"];
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
        };
        /** GeokodeOut */
        GeokodeOut: {
            /** Alamat */
            alamat: string;
            /** Desa */
            desa?: string | null;
            /** Kecamatan */
            kecamatan?: string | null;
            /** Kabupaten */
            kabupaten?: string | null;
            /** Provinsi */
            provinsi?: string | null;
            /** Kode Pos */
            kode_pos?: string | null;
            /** Sumber */
            sumber: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /**
         * IndeksMutuOut
         * @description K14 — penilaian mutu SISTEM, dihitung sebelum penerima memutuskan.
         *
         *     Seluruhnya dari data terpantau (telemetri suhu + waktu tempuh). Grade tiba
         *     sengaja tidak ikut: itu penilaian manusia yang baru ada setelah keputusan,
         *     dan memasukkannya akan membuat penerima bisa menggerakkan angkanya sendiri.
         */
        IndeksMutuOut: {
            /** Indeks Mutu */
            indeks_mutu: number;
            /** Penurunan Mutu Persen */
            penurunan_mutu_persen: number;
            /** Skor Umur Simpan */
            skor_umur_simpan: number;
            /** Skor Transit */
            skor_transit: number;
            /** Sisa Umur Simpan Persen */
            sisa_umur_simpan_persen?: number | null;
            /** Boleh Tolak */
            boleh_tolak: boolean;
            /** Ambang Tolak Persen */
            ambang_tolak_persen: number;
            /** Alasan Boleh Tolak */
            alasan_boleh_tolak: string;
        };
        /** KartuDampakOut */
        KartuDampakOut: {
            /** Nilai */
            nilai?: number | null;
            /** Satuan */
            satuan: string;
            /** Rumus */
            rumus: string;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
            /** Sub Teks */
            sub_teks?: string | null;
        };
        /**
         * KeputusanSerahTerima
         * @description K14: POTONG DIHAPUS. Penerima tidak boleh punya tuas komersial.
         *
         *     "Terima dengan potongan" membuat penerima bisa menekan harga sepihak dengan
         *     alasan mutu yang dia nilai sendiri — dan selama ini `persen_potongan` bahkan
         *     tidak pernah memengaruhi pembayaran, jadi ia murni ruang tawar-menawar tanpa
         *     akibat yang tercatat. Pilihannya kini hanya TERIMA atau TOLAK, dan TOLAK
         *     hanya terbuka kalau penurunan mutu yang DIUKUR SISTEM melewati ambang.
         * @enum {string}
         */
        KeputusanSerahTerima: "TERIMA" | "TOLAK";
        /** KirimanCreate */
        KirimanCreate: {
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Volume Kg */
            volume_kg: number;
            /**
             * Tanggal Siap
             * Format: date
             */
            tanggal_siap: string;
            /** Lat Tujuan */
            lat_tujuan: number;
            /** Lng Tujuan */
            lng_tujuan: number;
            /** Alamat Tujuan */
            alamat_tujuan: string;
            rincian_tujuan?: components["schemas"]["AlamatIn"] | null;
            /** Lat Asal */
            lat_asal?: number | null;
            /** Lng Asal */
            lng_asal?: number | null;
            rincian_asal?: components["schemas"]["AlamatIn"] | null;
        };
        /**
         * KirimanPratinjauResponse
         * @description Pratinjau §3.4 langkah 3: atap + potensi SEBELUM petani berkomitmen.
         */
        KirimanPratinjauResponse: {
            /** Harga Atap Per Kg */
            harga_atap_per_kg?: number | null;
            /** Harga Potensial Per Kg */
            harga_potensial_per_kg?: number | null;
            /** Slot Cocok Ada */
            slot_cocok_ada: boolean;
            /** Jarak Ke Penerima Km */
            jarak_ke_penerima_km?: number | null;
            /** Pesan */
            pesan?: string | null;
        };
        /** KirimanResponse */
        KirimanResponse: {
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Berjalan Per Kg */
            harga_berjalan_per_kg?: number | null;
            /** Jumlah Peserta */
            jumlah_peserta: number;
            /** Baru Dibuat */
            baru_dibuat: boolean;
        };
        /** KomoditasOut */
        KomoditasOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            /** Satuan */
            satuan: string;
            /** Harga Acuan Per Kg */
            harga_acuan_per_kg: number;
            /** Umur Simpan Jam */
            umur_simpan_jam: number;
            /** Laju Susut Per Jam */
            laju_susut_per_jam: number;
            /** Q10 */
            q10: number;
            /** Suhu Acuan C */
            suhu_acuan_c: number;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /** KonfigurasiOut */
        KonfigurasiOut: {
            /** Kunci */
            kunci: string;
            /** Nilai */
            nilai: string;
            tipe: components["schemas"]["TipeKonfigurasi"];
            /** Label */
            label: string;
            /** Satuan */
            satuan?: string | null;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /** KonfigurasiPatch */
        KonfigurasiPatch: {
            /** Nilai */
            nilai: string;
        };
        /** LotBeritaOut */
        LotBeritaOut: {
            lot: components["schemas"]["LotOut"];
            serah_terima?: components["schemas"]["SerahTerimaOut"] | null;
        };
        /** LotOut */
        LotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode Qr */
            kode_qr: string;
            /**
             * Partisipasi Id
             * Format: uuid
             */
            partisipasi_id: string;
            /** Slot Id */
            slot_id?: string | null;
            /** Nama Petani */
            nama_petani: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Penerima Id */
            penerima_id?: string | null;
            /** Nama Penerima */
            nama_penerima?: string | null;
            /** Berat Aktual Kg */
            berat_aktual_kg?: number | null;
            /** Foto Muat */
            foto_muat?: string | null;
            /** Waktu Muat */
            waktu_muat?: string | null;
            /** Catatan Muat */
            catatan_muat?: string | null;
            /** Grade Asal */
            grade_asal: number;
        };
        /**
         * LuapanKapasitasOut
         * @description Body 409 saat gabung memicu luapan (§5.5, K6) — bahan dialog dua pilihan.
         */
        LuapanKapasitasOut: {
            /**
             * Kode
             * @default LUAPAN_KAPASITAS
             */
            kode: string;
            /** Harga Baru Per Kg */
            harga_baru_per_kg: number;
            /** Jumlah Atap Terdampak */
            jumlah_atap_terdampak: number;
            /** Slot Alternatif Id */
            slot_alternatif_id?: string | null;
            /** Pesan */
            pesan: string;
        };
        /** MasukDemoRequest */
        MasukDemoRequest: {
            akun: components["schemas"]["AkunDemo"];
        };
        /** MasukRequest */
        MasukRequest: {
            /**
             * No Hp
             * @example 81234567001
             */
            no_hp: string;
            /**
             * Pin
             * @example 123456
             */
            pin: string;
        };
        /** MuatPatchRequest */
        MuatPatchRequest: {
            /** Berat Aktual Kg */
            berat_aktual_kg: number;
            /** Foto Muat Base64 */
            foto_muat_base64?: string | null;
            /**
             * Grade Asal
             * @default 5
             */
            grade_asal: number;
            /** Catatan Muat */
            catatan_muat?: string | null;
        };
        /**
         * OngkosPetaniOut
         * @description Rincian ongkos per petani (§9.8) — basis volume komitmen (K3).
         */
        OngkosPetaniOut: {
            /**
             * Partisipasi Id
             * Format: uuid
             */
            partisipasi_id: string;
            /** Nama Petani */
            nama_petani: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Final Per Kg */
            harga_final_per_kg: number;
            /** Tagihan Rp */
            tagihan_rp: number;
            /** Kembalian Rp */
            kembalian_rp: number;
        };
        /** PartisipasiOut */
        PartisipasiOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Petani Id
             * Format: uuid
             */
            petani_id: string;
            /** Nama Petani */
            nama_petani: string;
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /** Kembalian Rp */
            kembalian_rp: number;
            status: components["schemas"]["StatusPartisipasi"];
            /**
             * Bergabung Pada
             * Format: date-time
             */
            bergabung_pada: string;
        };
        /** PartisipasiRiwayatOut */
        PartisipasiRiwayatOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /** Slot Kode */
            slot_kode: string;
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /** Kembalian Rp */
            kembalian_rp: number;
            status: components["schemas"]["StatusPartisipasi"];
        };
        /** PenerimaOut */
        PenerimaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            tipe: components["schemas"]["TipePenerima"];
            /** Alamat */
            alamat: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** PenggunaOut */
        PenggunaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            /** No Hp */
            no_hp: string;
            peran: components["schemas"]["PeranPengguna"];
            /** Titik Kumpul Id */
            titik_kumpul_id?: string | null;
            /** Penerima Id */
            penerima_id?: string | null;
        };
        /** PengirimanOut */
        PengirimanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /** Vendor */
            vendor: string;
            /** Vendor Ref */
            vendor_ref?: string | null;
            /** Status Vendor */
            status_vendor?: string | null;
            timeline: components["schemas"]["TimelineOut"];
            /** Estimasi Tiba */
            estimasi_tiba?: string | null;
            /** Ambang Transit Menit */
            ambang_transit_menit: number;
            /** Jejak */
            jejak: components["schemas"]["PosisiOut"][];
        };
        /**
         * PeranPengguna
         * @enum {string}
         */
        PeranPengguna: "PETANI" | "PETUGAS" | "PENERIMA";
        /**
         * PerjalananResiOut
         * @description K14 — seluruh perjalanan satu resi dalam sekali panggil.
         *
         *     Penerima berhak melihat SELURUH data perjalanan sebelum memutuskan menerima
         *     atau menolak; sebelumnya ia hanya mendapat dua angka ringkas dan grafiknya
         *     cuma bisa dibuka peran lain.
         */
        PerjalananResiOut: {
            pengiriman: components["schemas"]["PengirimanOut"];
            telemetri: components["schemas"]["TelemetriOut"];
            titik_kumpul: components["schemas"]["TitikPetaOut"];
            /** Tujuan */
            tujuan: components["schemas"]["TitikPetaOut"][];
        };
        /** PosisiOut */
        PosisiOut: {
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /**
             * Waktu
             * Format: date-time
             */
            waktu: string;
            sumber: components["schemas"]["SumberPosisi"];
        };
        /**
         * RencanaArmadaOut
         * @description Rencana armada saat ini — sumber denominator bar kapasitas & petunjuk naik kelas tier (§9.4 butir 4).
         */
        RencanaArmadaOut: {
            /** Tier */
            tier: components["schemas"]["TierRingkasOut"][];
            /** Biaya Total */
            biaya_total: number;
            /** Kapasitas Total Kg */
            kapasitas_total_kg: number;
        };
        /**
         * RuteJemputOut
         * @description K14 — perhentian penjemputan, urut sesuai jalur petugas.
         *
         *     Inilah yang membuat peran petugas sebagai penghubung terlihat: dia mendapat
         *     daftar alamat yang harus didatangi, bukan cuma satu titik kumpul abstrak.
         */
        RuteJemputOut: {
            /** Urutan */
            urutan: number;
            /**
             * Partisipasi Id
             * Format: uuid
             */
            partisipasi_id: string;
            /** Nama Petani */
            nama_petani: string;
            /** Alamat */
            alamat: string;
            /** Jarak Segmen Km */
            jarak_segmen_km: number;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** RuteSegmenOut */
        RuteSegmenOut: {
            /** Urutan */
            urutan: number;
            /**
             * Penerima Id
             * Format: uuid
             */
            penerima_id: string;
            /** Nama Penerima */
            nama_penerima: string;
            /** Jarak Segmen Km */
            jarak_segmen_km: number;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * SerahTerimaCreate
         * @description K14: `persen_potongan` dihapus — hanya TERIMA atau TOLAK, tanpa tawar.
         */
        SerahTerimaCreate: {
            keputusan: components["schemas"]["KeputusanSerahTerima"];
            /** Alasan */
            alasan?: string | null;
            /** Foto Bongkar Base64 */
            foto_bongkar_base64?: string | null;
            /** Grade Tiba */
            grade_tiba: number;
        };
        /** SerahTerimaOut */
        SerahTerimaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /**
             * Penerima Id
             * Format: uuid
             */
            penerima_id: string;
            /**
             * Waktu Bongkar
             * Format: date-time
             */
            waktu_bongkar: string;
            /** Foto Bongkar */
            foto_bongkar?: string | null;
            keputusan: components["schemas"]["KeputusanSerahTerima"];
            /** Alasan */
            alasan?: string | null;
            /** Durasi Transit Menit */
            durasi_transit_menit: number;
            /** Ambang Transit Menit */
            ambang_transit_menit: number;
            atribusi: components["schemas"]["Atribusi"];
            /** Penjelasan */
            penjelasan: string;
            /** Grade Asal */
            grade_asal?: number | null;
            /** Grade Tiba */
            grade_tiba?: number | null;
            /** Sisa Umur Simpan Persen */
            sisa_umur_simpan_persen?: number | null;
            /** Indeks Mutu */
            indeks_mutu?: number | null;
        };
        /**
         * SlotDetailOut
         * @description Layar utama demo (§9.4). waktu_server = penangkal selisih jam perangkat.
         */
        SlotDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode */
            kode: string;
            status: components["schemas"]["StatusSlot"];
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /**
             * Cutoff Lewat
             * @default false
             */
            cutoff_lewat: boolean;
            /**
             * Waktu Server
             * Format: date-time
             */
            waktu_server: string;
            /** Jarak Km */
            jarak_km: number;
            titik_kumpul: components["schemas"]["TitikKumpulOut"];
            /**
             * Jemput
             * @default []
             */
            jemput: components["schemas"]["RuteJemputOut"][];
            /** Tujuan */
            tujuan: components["schemas"]["RuteSegmenOut"][];
            /** Volume Total Kg */
            volume_total_kg: number;
            /** Harga Berjalan Per Kg */
            harga_berjalan_per_kg?: number | null;
            rencana_saat_ini?: components["schemas"]["RencanaArmadaOut"] | null;
            /** Partisipasi */
            partisipasi: components["schemas"]["PartisipasiOut"][];
            /** Atap Saya Per Kg */
            atap_saya_per_kg?: number | null;
            /** Hemat Saya Per Kg */
            hemat_saya_per_kg?: number | null;
            /** Biaya Total */
            biaya_total?: number | null;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /**
             * Selisih Jaminan Atap
             * @default 0
             */
            selisih_jaminan_atap: number;
        };
        /**
         * SlotItemOut
         * @description Item daftar slot (Beranda §9.2) — bar kapasitas butuh numerator+denominator di sini.
         */
        SlotItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode */
            kode: string;
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /**
             * Cutoff Lewat
             * @default false
             */
            cutoff_lewat: boolean;
            status: components["schemas"]["StatusSlot"];
            /** Jarak Km */
            jarak_km: number;
            /** Volume Terkunci Kg */
            volume_terkunci_kg: number;
            /** Kapasitas Rencana Kg */
            kapasitas_rencana_kg?: number | null;
            /** Tier Ringkas */
            tier_ringkas?: string | null;
            /** Jumlah Petani */
            jumlah_petani: number;
        };
        /**
         * StatusPartisipasi
         * @enum {string}
         */
        StatusPartisipasi: "TERDAFTAR" | "TERKUNCI" | "DIMUAT" | "SELESAI" | "DITOLAK" | "BATAL";
        /**
         * StatusSlot
         * @enum {string}
         */
        StatusSlot: "DIBUKA" | "TERKUNCI" | "DIMUAT" | "JALAN" | "SELESAI" | "BATAL";
        /**
         * StatusSumber
         * @enum {string}
         */
        StatusSumber: "TERVERIFIKASI" | "ASUMSI";
        /**
         * SumberPosisi
         * @enum {string}
         */
        SumberPosisi: "HP_PENGAWAL" | "WEBHOOK_VENDOR" | "SIMULASI";
        /**
         * SumberTelemetri
         * @enum {string}
         */
        SumberTelemetri: "SIMULASI" | "SENSOR" | "HP_PETUGAS";
        /** TelemetriOut */
        TelemetriOut: {
            /** Sampel */
            sampel: components["schemas"]["TelemetriSampelOut"][];
            ringkasan?: components["schemas"]["TelemetriRingkasanOut"] | null;
        };
        /**
         * TelemetriRingkasanOut
         * @description Ringkasan paparan perjalanan — bahan 3 kartu + garis ambang di grafik (§5.4).
         */
        TelemetriRingkasanOut: {
            /** Suhu Maks C */
            suhu_maks_c: number;
            /** Suhu Rata C */
            suhu_rata_c: number;
            /** Kelembapan Rata Persen */
            kelembapan_rata_persen: number;
            /** Jam Ekivalen */
            jam_ekivalen: number;
            /** Sisa Umur Simpan Persen */
            sisa_umur_simpan_persen: number;
            /** Suhu Acuan C */
            suhu_acuan_c: number;
            /** Nama Komoditas */
            nama_komoditas?: string | null;
        };
        /** TelemetriSampelOut */
        TelemetriSampelOut: {
            /**
             * Waktu
             * Format: date-time
             */
            waktu: string;
            /** Suhu C */
            suhu_c: number;
            /** Kelembapan Persen */
            kelembapan_persen: number;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            sumber: components["schemas"]["SumberTelemetri"];
        };
        /** TierKendaraanOut */
        TierKendaraanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kapasitas Kg */
            kapasitas_kg: number;
            /** Tarif Dasar */
            tarif_dasar: number;
            /** Tarif Per Km */
            tarif_per_km: number;
            /** Urutan */
            urutan: number;
            /** Aktif */
            aktif: boolean;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /** TierKendaraanPatch */
        TierKendaraanPatch: {
            /** Kapasitas Kg */
            kapasitas_kg?: number | null;
            /** Tarif Dasar */
            tarif_dasar?: number | null;
            /** Tarif Per Km */
            tarif_per_km?: number | null;
            /** Aktif */
            aktif?: boolean | null;
        };
        /** TierRingkasOut */
        TierRingkasOut: {
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kapasitas Kg */
            kapasitas_kg: number;
        };
        /** TimelineOut */
        TimelineOut: {
            /** Dipesan */
            dipesan?: string | null;
            /** Dimuat */
            dimuat?: string | null;
            /** Berangkat */
            berangkat?: string | null;
            /** Tiba */
            tiba?: string | null;
        };
        /**
         * TipeKonfigurasi
         * @enum {string}
         */
        TipeKonfigurasi: "INT" | "FLOAT" | "STRING" | "BOOL";
        /**
         * TipePenerima
         * @enum {string}
         */
        TipePenerima: "SPPG" | "HOREKA" | "PENGOLAH" | "PASAR_INDUK";
        /**
         * TipeTitikKumpul
         * @enum {string}
         */
        TipeTitikKumpul: "PETANI_UTAMA" | "GAPOKTAN" | "KOPERASI" | "MITRA";
        /** TitikKumpulOut */
        TitikKumpulOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            /** Kode */
            kode?: string | null;
            tipe: components["schemas"]["TipeTitikKumpul"];
            /** Petugas Id */
            petugas_id?: string | null;
            /** Desa */
            desa?: string | null;
            /** Kecamatan */
            kecamatan?: string | null;
            /** Kabupaten */
            kabupaten?: string | null;
            /** Alamat */
            alamat: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** TitikPetaOut */
        TitikPetaOut: {
            /** Nama */
            nama: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
            pengguna: components["schemas"]["PenggunaOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WilayahOut */
        WilayahOut: {
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Tingkat */
            tingkat: string;
            /** Jalur */
            jalur: string;
            /** Kode Pos */
            kode_pos?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    masuk_api_auth_masuk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasukRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    masuk_demo_api_auth_masuk_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasukDemoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saya_api_auth_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaOut"];
                };
            };
        };
    };
    aturan_kiriman_api_aturan_kiriman_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AturanKirimanOut"];
                };
            };
        };
    };
    daftar_komoditas_api_komoditas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KomoditasOut"][];
                };
            };
        };
    };
    daftar_penerima_api_penerima_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenerimaOut"][];
                };
            };
        };
    };
    titik_kumpul_saya_api_titik_kumpul_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitikKumpulOut"];
                };
            };
        };
    };
    cari_wilayah_api_wilayah_cari_get: {
        parameters: {
            query: {
                /** @description Potongan nama desa/kecamatan/kabupaten */
                q: string;
                batas?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WilayahOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geokode_balik_endpoint_api_geokode_balik_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeokodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_konfigurasi_api_konfigurasi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonfigurasiOut"][];
                };
            };
        };
    };
    ubah_konfigurasi_api_konfigurasi__kunci__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kunci: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KonfigurasiPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonfigurasiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_tier_api_tier_kendaraan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierKendaraanOut"][];
                };
            };
        };
    };
    ubah_tier_api_tier_kendaraan__tier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TierKendaraanPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierKendaraanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kirim_panen_api_kiriman_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KirimanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KirimanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pratinjau_api_kiriman_pratinjau_get: {
        parameters: {
            query: {
                volume_kg: number;
                lat: number;
                lng: number;
                tanggal: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KirimanPratinjauResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_slot_api_slot_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["StatusSlot"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slot_tersedia_api_slot_tersedia_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotItemOut"][];
                };
            };
        };
    };
    terima_tugas_api_slot__slot_id__terima_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_slot_api_slot__slot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gabung_slot_api_slot__slot_id__gabung_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GabungRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GabungResponse"];
                };
            };
            /** @description LUAPAN_KAPASITAS (§5.5) — dialog dua pilihan */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LuapanKapasitasOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pratinjau_gabung_api_slot__slot_id__gabung_pratinjau_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GabungPratinjauRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GabungPratinjauResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tutup_slot_api_slot__slot_id__tutup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batal_slot_api_slot__slot_id__batal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_lot_slot_api_slot__slot_id__lot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    muat_lot_api_lot__lot_id__muat_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuatPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    selesai_muat_api_slot__slot_id__selesai_muat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lot_masuk_api_lot_masuk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuktiLotOut"][];
                };
            };
        };
    };
    bukti_lot_api_lot_qr__kode_qr__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kode_qr: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuktiLotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serah_terima_api_lot__lot_id__serah_terima_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerahTerimaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerahTerimaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pengiriman_slot_api_slot__slot_id__pengiriman_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PengirimanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telemetri_slot_api_lacak__slot_id__telemetri_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetriOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    perjalanan_resi_api_lacak_resi__kode_resi__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kode_resi: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerjalananResiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    majukan_pengiriman_api_pengiriman__pengiriman_id__majukan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pengiriman_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PengirimanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geser_posisi_api_pengiriman__pengiriman_id__geser_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pengiriman_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PengirimanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    berita_acara_api_slot__slot_id__berita_acara_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeritaAcaraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dampak_ringkasan_api_dampak_ringkasan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DampakRingkasanOut"];
                };
            };
        };
    };
    dampak_bulanan_api_dampak_bulanan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DampakBulananOut"][];
                };
            };
        };
    };
    partisipasi_saya_api_partisipasi_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartisipasiRiwayatOut"][];
                };
            };
        };
    };
    reset_demo_api_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResetOut"];
                };
            };
        };
    };
    berangkatkan_demo_api_demo_muatan__slot_id__berangkatkan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoBerangkatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
