/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/masuk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Masuk
         * @description Login nomor HP + PIN 6 digit (§9.1).
         */
        post: operations["masuk_api_auth_masuk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/masuk-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Masuk Demo
         * @description Masuk cepat (demo) — hanya aktif saat DEMO_MODE (§9.1, K6: 6 akun).
         */
        post: operations["masuk_demo_api_auth_masuk_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saya
         * @description Profil pengguna yang sedang login.
         */
        get: operations["saya_api_auth_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komoditas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Komoditas */
        get: operations["daftar_komoditas_api_komoditas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/penerima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Penerima */
        get: operations["daftar_penerima_api_penerima_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/koperasi/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Koperasi Saya
         * @description Koperasi milik pengguna login (gudang = titik awal rute).
         */
        get: operations["koperasi_saya_api_koperasi_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konfigurasi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Konfigurasi */
        get: operations["daftar_konfigurasi_api_konfigurasi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konfigurasi/{kunci}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah Konfigurasi */
        patch: operations["ubah_konfigurasi_api_konfigurasi__kunci__patch"];
        trace?: never;
    };
    "/api/tier-kendaraan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar Tier */
        get: operations["daftar_tier_api_tier_kendaraan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tier-kendaraan/{tier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah Tier */
        patch: operations["ubah_tier_api_tier_kendaraan__tier_id__patch"];
        trace?: never;
    };
    "/api/permintaan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Permintaan
         * @description Ter-scope per peran (K6): PENERIMA → miliknya; KOPERASI → semua yang terbuka.
         */
        get: operations["daftar_permintaan_api_permintaan_get"];
        put?: never;
        /** Buat Permintaan */
        post: operations["buat_permintaan_api_permintaan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Slot
         * @description Ter-scope per peran (K6): KOPERASI → miliknya; PETANI → slot koperasinya;
         *     PENERIMA → slot yang tujuannya memuat dirinya.
         */
        get: operations["daftar_slot_api_slot_get"];
        put?: never;
        /**
         * Buka Slot
         * @description Buka slot baru (§9.3). Server menghitung urutan drop nearest-neighbor + jarak_km.
         */
        post: operations["buka_slot_api_slot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/pratinjau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pratinjau Slot
         * @description Pratinjau §9.3: jarak rute + tabel harga/kg pada berbagai skenario volume.
         */
        post: operations["pratinjau_slot_api_slot_pratinjau_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail Slot
         * @description LAYAR UTAMA DEMO (§9.4). Dipoll 3 detik — harga berjalan, partisipasi,
         *     rencana armada, waktu_server.
         */
        get: operations["detail_slot_api_slot__slot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/gabung": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gabung Slot
         * @description 'Ikut kirim' — mengunci harga_atap_per_kg petani (tidak pernah berubah).
         */
        post: operations["gabung_slot_api_slot__slot_id__gabung_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/gabung/pratinjau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pratinjau Gabung
         * @description Peringatan dini sebelum submit: atap, harga berjalan baru, potensi luapan.
         */
        post: operations["pratinjau_gabung_api_slot__slot_id__gabung_pratinjau_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/tutup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tutup Slot
         * @description Cutoff (§5.4): tetapkan harga final + jaminan atap, kunci rencana armada,
         *     buat lot per partisipasi (alokasi penerima — K6), pesan ke vendor.
         */
        post: operations["tutup_slot_api_slot__slot_id__tutup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/batal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batal Slot */
        post: operations["batal_slot_api_slot__slot_id__batal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/lot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar Lot Slot
         * @description Daftar lot sebuah slot — layar Muat (§9.5).
         */
        get: operations["daftar_lot_slot_api_slot__slot_id__lot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/{lot_id}/muat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Muat Lot
         * @description Timbang + foto + checkbox 'Ada cacat terlihat' (input kunci atribusi §6).
         */
        patch: operations["muat_lot_api_lot__lot_id__muat_patch"];
        trace?: never;
    };
    "/api/slot/{slot_id}/selesai-muat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Selesai Muat
         * @description Selesai muat → slot JALAN, waktu berangkat tercatat (§9.5).
         */
        post: operations["selesai_muat_api_slot__slot_id__selesai_muat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/masuk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lot Masuk
         * @description 'Pilih dari daftar' (§9.7, K6): lot menuju penerima login yang belum
         *     diserahterimakan — jalur demo teraman.
         */
        get: operations["lot_masuk_api_lot_masuk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/qr/{kode_qr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bukti Lot
         * @description Bukti lot dari scan QR: foto muat, berat, waktu, transit berjalan vs ambang.
         */
        get: operations["bukti_lot_api_lot_qr__kode_qr__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lot/{lot_id}/serah-terima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Serah Terima
         * @description Terima / Terima dengan potongan / Tolak → atribusi + PENJELASAN (§6, §9.7).
         */
        post: operations["serah_terima_api_lot__lot_id__serah_terima_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/pengiriman": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pengiriman Slot
         * @description Timeline + estimasi tiba (dari ambang transit) + jejak posisi.
         */
        get: operations["pengiriman_slot_api_slot__slot_id__pengiriman_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pengiriman/{pengiriman_id}/majukan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Majukan Pengiriman
         * @description Majukan state simulasi MockVendor satu langkah (K5) — deterministik, untuk demo.
         */
        post: operations["majukan_pengiriman_api_pengiriman__pengiriman_id__majukan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slot/{slot_id}/berita-acara": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Berita Acara
         * @description Agregat: lot + foto muat & bongkar, keputusan, atribusi, rincian ongkos
         *     per petani, subsidi koperasi. Tanda tangan = garis kosong cetak (K4).
         */
        get: operations["berita_acara_api_slot__slot_id__berita_acara_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dampak/ringkasan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dampak Ringkasan
         * @description 4 kartu, masing-masing dengan rumus + status_sumber. Tanpa data = null → '—'.
         */
        get: operations["dampak_ringkasan_api_dampak_ringkasan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dampak/bulanan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dampak Bulanan
         * @description Grafik batang per bulan (Recharts) — termasuk jumlah_kiriman (K6).
         */
        get: operations["dampak_bulanan_api_dampak_bulanan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partisipasi/saya": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Partisipasi Saya
         * @description Riwayat ikut kirim + kembalian milik petani login.
         */
        get: operations["partisipasi_saya_api_partisipasi_saya_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Demo
         * @description Kembalikan database ke keadaan awal skenario demo. Idempoten, deterministik.
         */
        post: operations["reset_demo_api_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AkunDemo
         * @description 6 akun seed (KEPUTUSAN.md K6). UI menampilkan 4 tombol utama (§9.1);
         *     Dedi & Ijah dipakai skenario demo langkah 5–6.
         * @enum {string}
         */
        AkunDemo: "KOPERASI" | "PETANI_ASEP" | "PETANI_WATI" | "PETANI_DEDI" | "PETANI_IJAH" | "PENERIMA_CIBIRU";
        /**
         * Atribusi
         * @enum {string}
         */
        Atribusi: "PETANI" | "LOGISTIK" | "TIDAK_TERBUKTI";
        /** BeritaAcaraOut */
        BeritaAcaraOut: {
            /** Kode Slot */
            kode_slot: string;
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            koperasi: components["schemas"]["KoperasiOut"];
            /** Tujuan */
            tujuan: components["schemas"]["RuteSegmenOut"][];
            /** Lot */
            lot: components["schemas"]["LotBeritaOut"][];
            /** Rincian Ongkos */
            rincian_ongkos: components["schemas"]["OngkosPetaniOut"][];
            /** Biaya Total */
            biaya_total?: number | null;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /** Subsidi Koperasi */
            subsidi_koperasi: number;
            /**
             * Dibuat Pada
             * Format: date-time
             */
            dibuat_pada: string;
        };
        /**
         * BuktiLotOut
         * @description Respons GET /api/lot/qr/{kode_qr} — layar Serah Terima (§9.7).
         */
        BuktiLotOut: {
            lot: components["schemas"]["LotOut"];
            /** Durasi Transit Berjalan Menit */
            durasi_transit_berjalan_menit?: number | null;
            /** Ambang Transit Menit */
            ambang_transit_menit: number;
            serah_terima?: components["schemas"]["SerahTerimaOut"] | null;
        };
        /**
         * DampakBulananOut
         * @description Satu baris per bulan — juga sumber 'Ringkasan bulan ini' Beranda (§9.2, K6).
         */
        DampakBulananOut: {
            /** Bulan */
            bulan: string;
            /** Jumlah Kiriman */
            jumlah_kiriman: number;
            /** Penghematan Rp */
            penghematan_rp: number;
            /** Truk Km Dihemat */
            truk_km_dihemat: number;
            /** Emisi Kg */
            emisi_kg: number;
            /** Susut Kg */
            susut_kg?: number | null;
        };
        /** DampakRingkasanOut */
        DampakRingkasanOut: {
            truk_km_dihemat: components["schemas"]["KartuDampakOut"];
            emisi_dihemat_kg_co2: components["schemas"]["KartuDampakOut"];
            penghematan_ongkos_rp: components["schemas"]["KartuDampakOut"];
            susut_dicegah_kg: components["schemas"]["KartuDampakOut"];
        };
        /** DemoResetOut */
        DemoResetOut: {
            /** Pesan */
            pesan: string;
        };
        /** GabungPratinjauRequest */
        GabungPratinjauRequest: {
            /** Volume Kg */
            volume_kg: number;
        };
        /** GabungPratinjauResponse */
        GabungPratinjauResponse: {
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Berjalan Baru Per Kg */
            harga_berjalan_baru_per_kg: number;
            /** Luapan */
            luapan: boolean;
            /** Pesan */
            pesan?: string | null;
        };
        /** GabungRequest */
        GabungRequest: {
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Volume Kg */
            volume_kg: number;
        };
        /** GabungResponse */
        GabungResponse: {
            partisipasi: components["schemas"]["PartisipasiOut"];
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** KartuDampakOut */
        KartuDampakOut: {
            /** Nilai */
            nilai?: number | null;
            /** Satuan */
            satuan: string;
            /** Rumus */
            rumus: string;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /**
         * KeputusanSerahTerima
         * @enum {string}
         */
        KeputusanSerahTerima: "TERIMA" | "POTONG" | "TOLAK";
        /** KomoditasOut */
        KomoditasOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            /** Satuan */
            satuan: string;
            /** Harga Acuan Per Kg */
            harga_acuan_per_kg: number;
            /** Umur Simpan Jam */
            umur_simpan_jam: number;
            /** Laju Susut Per Jam */
            laju_susut_per_jam: number;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /** KonfigurasiOut */
        KonfigurasiOut: {
            /** Kunci */
            kunci: string;
            /** Nilai */
            nilai: string;
            tipe: components["schemas"]["TipeKonfigurasi"];
            /** Label */
            label: string;
            /** Satuan */
            satuan?: string | null;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /** KonfigurasiPatch */
        KonfigurasiPatch: {
            /** Nilai */
            nilai: string;
        };
        /** KoperasiOut */
        KoperasiOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            /** Kode */
            kode?: string | null;
            /** Desa */
            desa?: string | null;
            /** Kecamatan */
            kecamatan?: string | null;
            /** Kabupaten */
            kabupaten?: string | null;
            /** Alamat Gudang */
            alamat_gudang: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** LotBeritaOut */
        LotBeritaOut: {
            lot: components["schemas"]["LotOut"];
            serah_terima?: components["schemas"]["SerahTerimaOut"] | null;
        };
        /** LotOut */
        LotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode Qr */
            kode_qr: string;
            /**
             * Partisipasi Id
             * Format: uuid
             */
            partisipasi_id: string;
            /** Nama Petani */
            nama_petani: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Penerima Id */
            penerima_id?: string | null;
            /** Nama Penerima */
            nama_penerima?: string | null;
            /** Berat Aktual Kg */
            berat_aktual_kg?: number | null;
            /** Foto Muat */
            foto_muat?: string | null;
            /** Waktu Muat */
            waktu_muat?: string | null;
            /** Catatan Muat */
            catatan_muat?: string | null;
            /** Cacat Terlihat */
            cacat_terlihat: boolean;
        };
        /**
         * LuapanKapasitasOut
         * @description Body 409 saat gabung memicu luapan (§5.5, K6) — bahan dialog dua pilihan.
         */
        LuapanKapasitasOut: {
            /**
             * Kode
             * @default LUAPAN_KAPASITAS
             */
            kode: string;
            /** Harga Baru Per Kg */
            harga_baru_per_kg: number;
            /** Jumlah Atap Terdampak */
            jumlah_atap_terdampak: number;
            /** Slot Alternatif Id */
            slot_alternatif_id?: string | null;
            /** Pesan */
            pesan: string;
        };
        /** MasukDemoRequest */
        MasukDemoRequest: {
            akun: components["schemas"]["AkunDemo"];
        };
        /** MasukRequest */
        MasukRequest: {
            /**
             * No Hp
             * @example 81234567001
             */
            no_hp: string;
            /**
             * Pin
             * @example 123456
             */
            pin: string;
        };
        /** MuatPatchRequest */
        MuatPatchRequest: {
            /** Berat Aktual Kg */
            berat_aktual_kg: number;
            /** Foto Muat Base64 */
            foto_muat_base64?: string | null;
            /**
             * Cacat Terlihat
             * @default false
             */
            cacat_terlihat: boolean;
            /** Catatan Muat */
            catatan_muat?: string | null;
        };
        /**
         * OngkosPetaniOut
         * @description Rincian ongkos per petani (§9.8) — basis volume komitmen (K3).
         */
        OngkosPetaniOut: {
            /**
             * Partisipasi Id
             * Format: uuid
             */
            partisipasi_id: string;
            /** Nama Petani */
            nama_petani: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Final Per Kg */
            harga_final_per_kg: number;
            /** Tagihan Rp */
            tagihan_rp: number;
            /** Kembalian Rp */
            kembalian_rp: number;
        };
        /** PartisipasiOut */
        PartisipasiOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Petani Id
             * Format: uuid
             */
            petani_id: string;
            /** Nama Petani */
            nama_petani: string;
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /** Kembalian Rp */
            kembalian_rp: number;
            status: components["schemas"]["StatusPartisipasi"];
            /**
             * Bergabung Pada
             * Format: date-time
             */
            bergabung_pada: string;
        };
        /** PartisipasiRiwayatOut */
        PartisipasiRiwayatOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /** Slot Kode */
            slot_kode: string;
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Harga Atap Per Kg */
            harga_atap_per_kg: number;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /** Kembalian Rp */
            kembalian_rp: number;
            status: components["schemas"]["StatusPartisipasi"];
        };
        /** PenerimaOut */
        PenerimaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            tipe: components["schemas"]["TipePenerima"];
            /** Alamat */
            alamat: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** PenggunaOut */
        PenggunaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nama */
            nama: string;
            /** No Hp */
            no_hp: string;
            peran: components["schemas"]["PeranPengguna"];
            /** Koperasi Id */
            koperasi_id?: string | null;
            /** Penerima Id */
            penerima_id?: string | null;
        };
        /** PengirimanOut */
        PengirimanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Slot Id
             * Format: uuid
             */
            slot_id: string;
            /** Vendor */
            vendor: string;
            /** Vendor Ref */
            vendor_ref?: string | null;
            /** Status Vendor */
            status_vendor?: string | null;
            timeline: components["schemas"]["TimelineOut"];
            /** Estimasi Tiba */
            estimasi_tiba?: string | null;
            /** Ambang Transit Menit */
            ambang_transit_menit: number;
            /** Jejak */
            jejak: components["schemas"]["PosisiOut"][];
        };
        /**
         * PeranPengguna
         * @enum {string}
         */
        PeranPengguna: "PETANI" | "KOPERASI" | "PENERIMA";
        /** PermintaanCreate */
        PermintaanCreate: {
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Volume Kg */
            volume_kg: number;
            /**
             * Tanggal Dibutuhkan
             * Format: date
             */
            tanggal_dibutuhkan: string;
        };
        /** PermintaanOut */
        PermintaanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Penerima Id
             * Format: uuid
             */
            penerima_id: string;
            /** Nama Penerima */
            nama_penerima: string;
            /**
             * Komoditas Id
             * Format: uuid
             */
            komoditas_id: string;
            /** Nama Komoditas */
            nama_komoditas: string;
            /** Volume Kg */
            volume_kg: number;
            /** Volume Terpenuhi Kg */
            volume_terpenuhi_kg: number;
            /**
             * Tanggal Dibutuhkan
             * Format: date
             */
            tanggal_dibutuhkan: string;
            status: components["schemas"]["StatusPermintaan"];
            /** Slot Id */
            slot_id?: string | null;
            /**
             * Dibuat Pada
             * Format: date-time
             */
            dibuat_pada: string;
        };
        /** PosisiOut */
        PosisiOut: {
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /**
             * Waktu
             * Format: date-time
             */
            waktu: string;
            sumber: components["schemas"]["SumberPosisi"];
        };
        /** PratinjauSlotRequest */
        PratinjauSlotRequest: {
            /** Tujuan */
            tujuan: string[];
            /**
             * Skenario Volume
             * @description mis. [300, 800, 2000]
             */
            skenario_volume: number[];
        };
        /** PratinjauSlotResponse */
        PratinjauSlotResponse: {
            /** Jarak Km */
            jarak_km: number;
            /** Rute */
            rute: components["schemas"]["RuteSegmenOut"][];
            /** Tabel Harga */
            tabel_harga: components["schemas"]["SkenarioHargaOut"][];
        };
        /**
         * RencanaArmadaOut
         * @description Rencana armada saat ini — sumber denominator bar kapasitas & petunjuk naik kelas tier (§9.4 butir 4).
         */
        RencanaArmadaOut: {
            /** Tier */
            tier: components["schemas"]["TierRingkasOut"][];
            /** Biaya Total */
            biaya_total: number;
            /** Kapasitas Total Kg */
            kapasitas_total_kg: number;
        };
        /** RuteSegmenOut */
        RuteSegmenOut: {
            /** Urutan */
            urutan: number;
            /**
             * Penerima Id
             * Format: uuid
             */
            penerima_id: string;
            /** Nama Penerima */
            nama_penerima: string;
            /** Jarak Segmen Km */
            jarak_segmen_km: number;
        };
        /** SerahTerimaCreate */
        SerahTerimaCreate: {
            keputusan: components["schemas"]["KeputusanSerahTerima"];
            /**
             * Persen Potongan
             * @default 0
             */
            persen_potongan: number;
            /** Alasan */
            alasan?: string | null;
            /** Foto Bongkar Base64 */
            foto_bongkar_base64?: string | null;
        };
        /** SerahTerimaOut */
        SerahTerimaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lot Id
             * Format: uuid
             */
            lot_id: string;
            /**
             * Penerima Id
             * Format: uuid
             */
            penerima_id: string;
            /**
             * Waktu Bongkar
             * Format: date-time
             */
            waktu_bongkar: string;
            keputusan: components["schemas"]["KeputusanSerahTerima"];
            /** Persen Potongan */
            persen_potongan: number;
            /** Alasan */
            alasan?: string | null;
            /** Durasi Transit Menit */
            durasi_transit_menit: number;
            /** Ambang Transit Menit */
            ambang_transit_menit: number;
            atribusi: components["schemas"]["Atribusi"];
            /** Penjelasan */
            penjelasan: string;
        };
        /** SkenarioHargaOut */
        SkenarioHargaOut: {
            /** Volume Kg */
            volume_kg: number;
            /** Harga Per Kg */
            harga_per_kg: number;
            /** Biaya Total */
            biaya_total: number;
            /** Kendaraan */
            kendaraan: string[];
        };
        /** SlotCreate */
        SlotCreate: {
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /**
             * Tujuan
             * @description penerima_id, urutan drop dihitung server (nearest-neighbor)
             */
            tujuan: string[];
            /**
             * Permintaan Ids
             * @description permintaan yang hendak dipenuhi slot ini (K6)
             */
            permintaan_ids?: string[];
        };
        /**
         * SlotDetailOut
         * @description Layar utama demo (§9.4). waktu_server = penangkal selisih jam perangkat.
         */
        SlotDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode */
            kode: string;
            status: components["schemas"]["StatusSlot"];
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            /**
             * Waktu Server
             * Format: date-time
             */
            waktu_server: string;
            /** Jarak Km */
            jarak_km: number;
            koperasi: components["schemas"]["KoperasiOut"];
            /** Tujuan */
            tujuan: components["schemas"]["RuteSegmenOut"][];
            /** Volume Total Kg */
            volume_total_kg: number;
            /** Harga Berjalan Per Kg */
            harga_berjalan_per_kg?: number | null;
            rencana_saat_ini?: components["schemas"]["RencanaArmadaOut"] | null;
            /** Partisipasi */
            partisipasi: components["schemas"]["PartisipasiOut"][];
            /** Atap Saya Per Kg */
            atap_saya_per_kg?: number | null;
            /** Hemat Saya Per Kg */
            hemat_saya_per_kg?: number | null;
            /** Biaya Total */
            biaya_total?: number | null;
            /** Harga Final Per Kg */
            harga_final_per_kg?: number | null;
            /**
             * Subsidi Koperasi
             * @default 0
             */
            subsidi_koperasi: number;
        };
        /**
         * SlotItemOut
         * @description Item daftar slot (Beranda §9.2) — bar kapasitas butuh numerator+denominator di sini.
         */
        SlotItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode */
            kode: string;
            /**
             * Tanggal Kirim
             * Format: date
             */
            tanggal_kirim: string;
            /**
             * Cutoff At
             * Format: date-time
             */
            cutoff_at: string;
            status: components["schemas"]["StatusSlot"];
            /** Jarak Km */
            jarak_km: number;
            /** Volume Terkunci Kg */
            volume_terkunci_kg: number;
            /** Kapasitas Rencana Kg */
            kapasitas_rencana_kg?: number | null;
            /** Tier Ringkas */
            tier_ringkas?: string | null;
            /** Jumlah Petani */
            jumlah_petani: number;
        };
        /**
         * StatusPartisipasi
         * @enum {string}
         */
        StatusPartisipasi: "TERDAFTAR" | "TERKUNCI" | "DIMUAT" | "SELESAI" | "BATAL";
        /**
         * StatusPermintaan
         * @enum {string}
         */
        StatusPermintaan: "TERBUKA" | "TERPENUHI_SEBAGIAN" | "TERPENUHI" | "KEDALUWARSA";
        /**
         * StatusSlot
         * @enum {string}
         */
        StatusSlot: "DIBUKA" | "TERKUNCI" | "DIMUAT" | "JALAN" | "SELESAI" | "BATAL";
        /**
         * StatusSumber
         * @enum {string}
         */
        StatusSumber: "TERVERIFIKASI" | "ASUMSI";
        /**
         * SumberPosisi
         * @enum {string}
         */
        SumberPosisi: "HP_PENGAWAL" | "WEBHOOK_VENDOR" | "SIMULASI";
        /** TierKendaraanOut */
        TierKendaraanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kapasitas Kg */
            kapasitas_kg: number;
            /** Tarif Dasar */
            tarif_dasar: number;
            /** Tarif Per Km */
            tarif_per_km: number;
            /** Urutan */
            urutan: number;
            /** Aktif */
            aktif: boolean;
            status_sumber: components["schemas"]["StatusSumber"];
            /** Catatan Sumber */
            catatan_sumber?: string | null;
        };
        /** TierKendaraanPatch */
        TierKendaraanPatch: {
            /** Kapasitas Kg */
            kapasitas_kg?: number | null;
            /** Tarif Dasar */
            tarif_dasar?: number | null;
            /** Tarif Per Km */
            tarif_per_km?: number | null;
            /** Aktif */
            aktif?: boolean | null;
        };
        /** TierRingkasOut */
        TierRingkasOut: {
            /** Kode */
            kode: string;
            /** Nama */
            nama: string;
            /** Kapasitas Kg */
            kapasitas_kg: number;
        };
        /** TimelineOut */
        TimelineOut: {
            /** Dipesan */
            dipesan?: string | null;
            /** Dimuat */
            dimuat?: string | null;
            /** Berangkat */
            berangkat?: string | null;
            /** Tiba */
            tiba?: string | null;
        };
        /**
         * TipeKonfigurasi
         * @enum {string}
         */
        TipeKonfigurasi: "INT" | "FLOAT" | "STRING" | "BOOL";
        /**
         * TipePenerima
         * @enum {string}
         */
        TipePenerima: "SPPG" | "HOREKA" | "PENGOLAH" | "PASAR_INDUK";
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
            pengguna: components["schemas"]["PenggunaOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    masuk_api_auth_masuk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasukRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    masuk_demo_api_auth_masuk_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasukDemoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saya_api_auth_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenggunaOut"];
                };
            };
        };
    };
    daftar_komoditas_api_komoditas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KomoditasOut"][];
                };
            };
        };
    };
    daftar_penerima_api_penerima_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenerimaOut"][];
                };
            };
        };
    };
    koperasi_saya_api_koperasi_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KoperasiOut"];
                };
            };
        };
    };
    daftar_konfigurasi_api_konfigurasi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonfigurasiOut"][];
                };
            };
        };
    };
    ubah_konfigurasi_api_konfigurasi__kunci__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kunci: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KonfigurasiPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonfigurasiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_tier_api_tier_kendaraan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierKendaraanOut"][];
                };
            };
        };
    };
    ubah_tier_api_tier_kendaraan__tier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TierKendaraanPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierKendaraanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_permintaan_api_permintaan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermintaanOut"][];
                };
            };
        };
    };
    buat_permintaan_api_permintaan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermintaanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermintaanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_slot_api_slot_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["StatusSlot"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buka_slot_api_slot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pratinjau_slot_api_slot_pratinjau_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PratinjauSlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PratinjauSlotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_slot_api_slot__slot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gabung_slot_api_slot__slot_id__gabung_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GabungRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GabungResponse"];
                };
            };
            /** @description LUAPAN_KAPASITAS (§5.5) — dialog dua pilihan */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LuapanKapasitasOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pratinjau_gabung_api_slot__slot_id__gabung_pratinjau_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GabungPratinjauRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GabungPratinjauResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tutup_slot_api_slot__slot_id__tutup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batal_slot_api_slot__slot_id__batal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daftar_lot_slot_api_slot__slot_id__lot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    muat_lot_api_lot__lot_id__muat_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuatPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    selesai_muat_api_slot__slot_id__selesai_muat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lot_masuk_api_lot_masuk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuktiLotOut"][];
                };
            };
        };
    };
    bukti_lot_api_lot_qr__kode_qr__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kode_qr: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuktiLotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serah_terima_api_lot__lot_id__serah_terima_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerahTerimaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerahTerimaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pengiriman_slot_api_slot__slot_id__pengiriman_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PengirimanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    majukan_pengiriman_api_pengiriman__pengiriman_id__majukan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pengiriman_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PengirimanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    berita_acara_api_slot__slot_id__berita_acara_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeritaAcaraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dampak_ringkasan_api_dampak_ringkasan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DampakRingkasanOut"];
                };
            };
        };
    };
    dampak_bulanan_api_dampak_bulanan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DampakBulananOut"][];
                };
            };
        };
    };
    partisipasi_saya_api_partisipasi_saya_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartisipasiRiwayatOut"][];
                };
            };
        };
    };
    reset_demo_api_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResetOut"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
