"""skema awal 14 tabel

Revision ID: 1c78e6ed77bb
Revises: 
Create Date: 2026-07-27 00:18:48.629537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c78e6ed77bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('komoditas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('satuan', sa.Text(), server_default='kg', nullable=False),
    sa.Column('harga_acuan_per_kg', sa.Integer(), nullable=False),
    sa.Column('umur_simpan_jam', sa.Integer(), nullable=False),
    sa.Column('laju_susut_per_jam', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('status_sumber', sa.Enum('TERVERIFIKASI', 'ASUMSI', name='status_sumber'), nullable=False),
    sa.Column('catatan_sumber', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('konfigurasi',
    sa.Column('kunci', sa.Text(), nullable=False),
    sa.Column('nilai', sa.Text(), nullable=False),
    sa.Column('tipe', sa.Enum('INT', 'FLOAT', 'STRING', 'BOOL', name='tipe_konfigurasi'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('satuan', sa.Text(), nullable=True),
    sa.Column('status_sumber', sa.Enum('TERVERIFIKASI', 'ASUMSI', name='status_sumber'), nullable=False),
    sa.Column('catatan_sumber', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kunci')
    )
    op.create_table('koperasi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('kode', sa.Text(), nullable=True),
    sa.Column('desa', sa.Text(), nullable=True),
    sa.Column('kecamatan', sa.Text(), nullable=True),
    sa.Column('kabupaten', sa.Text(), nullable=True),
    sa.Column('alamat_gudang', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('penerima',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('tipe', sa.Enum('SPPG', 'HOREKA', 'PENGOLAH', 'PASAR_INDUK', name='tipe_penerima'), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tier_kendaraan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.Text(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('kapasitas_kg', sa.Integer(), nullable=False),
    sa.Column('tarif_dasar', sa.Integer(), nullable=False),
    sa.Column('tarif_per_km', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status_sumber', sa.Enum('TERVERIFIKASI', 'ASUMSI', name='status_sumber'), nullable=False),
    sa.Column('catatan_sumber', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('no_hp', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=False),
    sa.Column('peran', sa.Enum('PETANI', 'KOPERASI', 'PENERIMA', name='peran_pengguna'), nullable=False),
    sa.Column('koperasi_id', sa.UUID(), nullable=True),
    sa.Column('penerima_id', sa.UUID(), nullable=True),
    sa.Column('aktif', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['koperasi_id'], ['koperasi.id'], ),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_hp')
    )
    op.create_table('slot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.Text(), nullable=False),
    sa.Column('koperasi_id', sa.UUID(), nullable=False),
    sa.Column('tanggal_kirim', sa.Date(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DIBUKA', 'TERKUNCI', 'DIMUAT', 'JALAN', 'SELESAI', 'BATAL', name='status_slot'), nullable=False),
    sa.Column('jarak_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tier_terpilih_id', sa.UUID(), nullable=True),
    sa.Column('jumlah_kendaraan', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rencana_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('biaya_total', sa.Integer(), nullable=True),
    sa.Column('harga_final_per_kg', sa.Integer(), nullable=True),
    sa.Column('subsidi_koperasi', sa.Integer(), server_default='0', nullable=False),
    sa.Column('volume_terkunci_kg', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['koperasi_id'], ['koperasi.id'], ),
    sa.ForeignKeyConstraint(['tier_terpilih_id'], ['tier_kendaraan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('partisipasi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('petani_id', sa.UUID(), nullable=False),
    sa.Column('komoditas_id', sa.UUID(), nullable=False),
    sa.Column('volume_kg', sa.Integer(), nullable=False),
    sa.Column('harga_atap_per_kg', sa.Integer(), nullable=False),
    sa.Column('harga_final_per_kg', sa.Integer(), nullable=True),
    sa.Column('kembalian_rp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('TERDAFTAR', 'TERKUNCI', 'DIMUAT', 'SELESAI', 'BATAL', name='status_partisipasi'), nullable=False),
    sa.Column('bergabung_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['komoditas_id'], ['komoditas.id'], ),
    sa.ForeignKeyConstraint(['petani_id'], ['pengguna.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'petani_id', 'komoditas_id')
    )
    op.create_table('pengiriman',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('vendor_ref', sa.Text(), nullable=True),
    sa.Column('status_vendor', sa.Text(), nullable=True),
    sa.Column('waktu_berangkat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waktu_tiba', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kuotasi_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_table('permintaan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('penerima_id', sa.UUID(), nullable=False),
    sa.Column('komoditas_id', sa.UUID(), nullable=False),
    sa.Column('volume_kg', sa.Integer(), nullable=False),
    sa.Column('tanggal_dibutuhkan', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('TERBUKA', 'TERPENUHI_SEBAGIAN', 'TERPENUHI', 'KEDALUWARSA', name='status_permintaan'), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('volume_terpenuhi_kg', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['komoditas_id'], ['komoditas.id'], ),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_tujuan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('penerima_id', sa.UUID(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('jarak_segmen_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'urutan')
    )
    op.create_table('jejak_posisi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pengiriman_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sumber', sa.Enum('HP_PENGAWAL', 'WEBHOOK_VENDOR', 'SIMULASI', name='sumber_posisi'), nullable=False),
    sa.ForeignKeyConstraint(['pengiriman_id'], ['pengiriman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partisipasi_id', sa.UUID(), nullable=False),
    sa.Column('kode_qr', sa.Text(), nullable=False),
    sa.Column('penerima_id', sa.UUID(), nullable=True),
    sa.Column('berat_aktual_kg', sa.Integer(), nullable=True),
    sa.Column('foto_muat', sa.Text(), nullable=True),
    sa.Column('waktu_muat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catatan_muat', sa.Text(), nullable=True),
    sa.Column('cacat_terlihat', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['partisipasi_id'], ['partisipasi.id'], ),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_qr')
    )
    op.create_table('serah_terima',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('penerima_id', sa.UUID(), nullable=False),
    sa.Column('waktu_bongkar', sa.DateTime(timezone=True), nullable=False),
    sa.Column('foto_bongkar', sa.Text(), nullable=True),
    sa.Column('keputusan', sa.Enum('TERIMA', 'POTONG', 'TOLAK', name='keputusan_serah_terima'), nullable=False),
    sa.Column('persen_potongan', sa.Integer(), server_default='0', nullable=False),
    sa.Column('alasan', sa.Text(), nullable=True),
    sa.Column('durasi_transit_menit', sa.Integer(), nullable=False),
    sa.Column('ambang_transit_menit', sa.Integer(), nullable=False),
    sa.Column('atribusi', sa.Enum('PETANI', 'LOGISTIK', 'TIDAK_TERBUKTI', name='atribusi'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serah_terima')
    op.drop_table('lot')
    op.drop_table('jejak_posisi')
    op.drop_table('slot_tujuan')
    op.drop_table('permintaan')
    op.drop_table('pengiriman')
    op.drop_table('partisipasi')
    op.drop_table('slot')
    op.drop_table('pengguna')
    op.drop_table('tier_kendaraan')
    op.drop_table('penerima')
    op.drop_table('koperasi')
    op.drop_table('konfigurasi')
    op.drop_table('komoditas')
    # ### end Alembic commands ###
